version: '2'

services:
  db:
    image: postgres:18.1
    container_name: db
    environment:
      POSTGRES_DB: quizmania
      POSTGRES_USER: quizmania
      POSTGRES_PASSWORD: quizmania
    ports:
      - '5432:5432'
  axonserver:
    image: axoniq/axonserver:2026.1.4-jdk-21
    hostname: axonserver
    environment:
      AXONIQ_AXONSERVER_STANDALONE_DCB: "true"
    #    volumes:
#      - axonserver-data:/data
#      - axonserver-events:/eventdata
#      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
